'use client';

import React, { useState } from 'react';
import { useGraphStore } from '@/store/graph.store';
import { synthesisApi } from '@/lib/api';
import { X, Sparkles, Loader2, ArrowRight, Copy, Check, FileDown } from 'lucide-react';

interface SynthesisModalProps {
    onClose: () => void;
}

export default function SynthesisModal({ onClose }: SynthesisModalProps) {
    const { nodes, addNode, activeWhiteboardId } = useGraphStore();
    const [query, setQuery] = useState('');
    const [result, setResult] = useState('');
    const [sources, setSources] = useState<string[]>([]);
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const [saving, setSaving] = useState(false);

    // Get all selected nodes
    const selectedNodes = nodes.filter(n => n.selected);
    const selectedCount = selectedNodes.length > 0 ? selectedNodes.length : nodes.length;

    const handleSynthesize = async () => {
        if (!query.trim()) return;

        setLoading(true);
        setResult('');
        setSources([]);

        try {
            const nodeIds = selectedNodes.length > 0
                ? selectedNodes.map(n => n.id)
                : nodes.map(n => n.id);

            const response = await synthesisApi.generate({
                node_ids: nodeIds,
                query: query.trim(),
                previous_summary: result || undefined
            });

            setResult(response.summary);
            setSources(response.sources);
            setQuery(''); // Clear query for next refinement
        } catch (e) {
            console.error('Synthesis error:', e);
            setResult('Error generating synthesis. Make sure the backend is running.');
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(result);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSaveToCanvas = async () => {
        if (!result) return;
        setSaving(true);
        try {
            const nodeId = `synthesis-${Date.now()}`;
            const newNode = {
                id: nodeId,
                type: 'synthesis',
                position: { x: 100, y: 100 }, // Initial position, user can move it
                data: {
                    title: query || 'AI Synthesis',
                    summary: result,
                    sourceCount: sources.length,
                    whiteboard_id: activeWhiteboardId
                },
            };

            await addNode(newNode as any);
            // Optionally close the modal or show success
            setResult('');
            setQuery('');
            onClose();
        } catch (e) {
            console.error('Failed to save synthesis:', e);
        } finally {
            setSaving(false);
        }
    };

    const handleDownloadMarkdown = () => {
        if (!result) return;

        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const filename = `synthesis-${timestamp}.md`;

        const content = `# AI Synthesis: ${query || 'Research Report'}
---
**Sources:** ${sources.join(', ') || 'All nodes'}
**Date:** ${new Date().toLocaleString()}

## Analysis
${result}

---
*Generated by Rabbit Hole OS*`;

        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="absolute bottom-4 left-4 right-20 z-20">
            <div className="bg-neutral-900/95 backdrop-blur-xl border border-neutral-800 rounded-2xl shadow-2xl overflow-hidden">
                {/* Header */}
                <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-800">
                    <div className="flex items-center gap-2">
                        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-green-500 to-green-600 flex items-center justify-center">
                            <Sparkles size={16} className="text-white" />
                        </div>
                        <div>
                            <h2 className="text-sm font-semibold text-white">SYNTHESIS ACTIVE</h2>
                            <p className="text-xs text-neutral-400">{selectedCount} items selected</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-1.5 hover:bg-neutral-800 rounded-lg text-neutral-400 hover:text-white transition-colors"
                    >
                        <X size={16} />
                    </button>
                </div>

                {/* Input Area */}
                <div className="p-4">
                    <div className="flex gap-3">
                        <input
                            type="text"
                            placeholder="Compare these sources on..."
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleSynthesize()}
                            className="flex-1 bg-neutral-800 border border-neutral-700 rounded-xl px-4 py-3 text-sm text-white placeholder-neutral-500 focus:outline-none focus:border-green-500 transition-colors"
                        />
                        <button
                            onClick={handleSynthesize}
                            disabled={loading || !query.trim()}
                            className="px-4 py-3 bg-gradient-to-r from-green-500 to-green-600 text-white font-medium rounded-xl flex items-center gap-2 hover:from-green-600 hover:to-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                        >
                            {loading ? (
                                <Loader2 size={16} className="animate-spin" />
                            ) : (
                                <>
                                    {result ? 'REFINE' : 'RUN'} <ArrowRight size={14} />
                                </>
                            )}
                        </button>
                    </div>

                    {/* Result */}
                    {result && (
                        <div className="mt-4">
                            {/* Sources */}
                            {sources.length > 0 && (
                                <div className="flex items-center gap-2 mb-2 flex-wrap">
                                    <span className="text-xs text-neutral-500">Sources:</span>
                                    {sources.map((source, i) => (
                                        <span key={i} className="px-2 py-0.5 text-xs bg-neutral-800 text-neutral-400 rounded">
                                            {source}
                                        </span>
                                    ))}
                                </div>
                            )}

                            {/* Content */}
                            <div className="p-4 bg-neutral-800/50 rounded-xl border border-neutral-700 relative">
                                <div className="prose prose-sm prose-invert max-w-none">
                                    <div className="text-sm text-neutral-200 leading-relaxed whitespace-pre-wrap">
                                        {result}
                                    </div>
                                </div>

                                <div className="absolute top-2 right-2 flex gap-1">
                                    <button
                                        onClick={handleDownloadMarkdown}
                                        className="p-2 hover:bg-neutral-700 rounded-lg text-neutral-400 hover:text-blue-400 transition-colors"
                                        title="Download Markdown"
                                    >
                                        <FileDown size={14} />
                                    </button>
                                    <button
                                        onClick={handleSaveToCanvas}
                                        disabled={saving}
                                        className="p-2 hover:bg-neutral-700 rounded-lg text-neutral-400 hover:text-green-400 transition-colors flex items-center gap-1.5 text-xs font-medium"
                                        title="Save to Canvas"
                                    >
                                        {saving ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                                        SAVE TO CANVAS
                                    </button>
                                    <button
                                        onClick={handleCopy}
                                        className="p-2 hover:bg-neutral-700 rounded-lg text-neutral-400 hover:text-white transition-colors"
                                        title="Copy to Clipboard"
                                    >
                                        {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
