'use client';

import React, { useState, useEffect } from 'react';
import { useGraphStore } from '@/store/graph.store';
import { synthesisApi } from '@/lib/api';
import { Sparkles, Loader2, ArrowRight, Copy, Check, FileDown, Target, Link2, Search, Share2 } from 'lucide-react';
import { Node } from 'reactflow';
import { motion, AnimatePresence } from 'framer-motion';

interface SynthesisModalProps {
    onClose: () => void;
}

const STEPS = [
    { id: 'ingesting', label: 'Ingesting', icon: <Search size={11} /> },
    { id: 'linking', label: 'Linking', icon: <Link2 size={11} /> },
    { id: 'synthesizing', label: 'Synthesizing', icon: <Sparkles size={11} /> },
    { id: 'publishing', label: 'Publishing', icon: <Share2 size={11} /> },
];

export default function SynthesisModal({ onClose }: SynthesisModalProps) {
    const { nodes, addNode, activeWhiteboardId } = useGraphStore();
    const [query, setQuery] = useState('');
    const [result, setResult] = useState('');
    const [sources, setSources] = useState<string[]>([]);
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const [saving, setSaving] = useState(false);
    const [progress, setProgress] = useState(0);
    const [activeStepIndex, setActiveStepIndex] = useState(0);

    // Get all selected nodes
    const selectedNodes = nodes.filter(n => n.selected);
    const selectedCount = selectedNodes.length > 0 ? selectedNodes.length : nodes.length;

    // Simulated progress animation
    useEffect(() => {
        let timer: NodeJS.Timeout;
        if (loading) {
            setProgress(0);
            setActiveStepIndex(0);
            
            const animate = () => {
                setProgress(prev => {
                    if (prev >= 95) return prev;
                    const increment = Math.random() * 5;
                    const next = prev + increment;
                    
                    // Update active step based on progress
                    if (next < 25) setActiveStepIndex(0);
                    else if (next < 50) setActiveStepIndex(1);
                    else if (next < 85) setActiveStepIndex(2);
                    else setActiveStepIndex(3);
                    
                    return next;
                });
                timer = setTimeout(animate, 500 + Math.random() * 1000);
            };
            animate();
        }
        return () => clearTimeout(timer);
    }, [loading]);

    const handleSynthesize = async () => {
        if (!query.trim()) return;

        setLoading(true);
        setResult('');
        setSources([]);

        try {
            const nodeIds = selectedNodes.length > 0
                ? selectedNodes.map(n => n.id)
                : nodes.map(n => n.id);

            const response = await synthesisApi.generate({
                node_ids: nodeIds,
                query: query.trim(),
                previous_summary: result || undefined
            });

            // Finish the progress
            setProgress(100);
            setActiveStepIndex(3);
            
            // Short delay to show 100%
            await new Promise(r => setTimeout(r, 600));

            setResult(response.summary);
            setSources(response.sources);
            // setQuery(''); // Keep query for refinement if needed
        } catch (e) {
            console.error('Synthesis error:', e);
            setResult('Error generating synthesis. Make sure the backend is running.');
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(result);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleSaveToCanvas = async () => {
        if (!result) return;
        setSaving(true);
        try {
            const nodeId = `synthesis-${Date.now()}`;
            const newNode = {
                id: nodeId,
                type: 'synthesis',
                position: { x: 100, y: 100 },
                data: {
                    title: query || 'AI Synthesis',
                    summary: result,
                    sourceCount: sources.length,
                    whiteboard_id: activeWhiteboardId
                },
            };

            await addNode(newNode as unknown as Node);
            onClose();
        } catch (e) {
            console.error('Failed to save synthesis:', e);
        } finally {
            setSaving(false);
        }
    };

    const handleDownloadMarkdown = () => {
        if (!result) return;
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const filename = `synthesis-${timestamp}.md`;
        const content = `# AI Synthesis: ${query || 'Research Report'}\n---\n**Sources:** ${sources.join(', ') || 'All nodes'}\n**Date:** ${new Date().toLocaleString()}\n\n## Analysis\n${result}\n\n---\n*Generated by Rabbit Hole OS*`;
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <AnimatePresence>
            <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center p-6 font-[Syne]"
            >
                {/* Backdrop / Blur */}
                <div 
                    className="absolute inset-0 bg-(--bg)/80 backdrop-blur-md cursor-default"
                    onClick={onClose}
                />

                {/* Background Layer */}
                <div className="absolute inset-0 z-0 pointer-events-none overflow-hidden">
                    <motion.div 
                        animate={{ scale: [1, 1.1, 1], opacity: [0.7, 1, 0.7] }}
                        transition={{ duration: 4, ease: 'linear', repeat: Infinity }}
                        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] rounded-full bg-[radial-gradient(circle,rgba(232,160,32,0.06)_0%,transparent_65%)]"
                    />
                    <div className="absolute inset-0 opacity-[0.035] pointer-events-none" 
                        style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E")` }}
                    />
                </div>

                {/* Modal Content */}
                <motion.div
                    initial={{ scale: 0.9, opacity: 0, y: 20 }}
                    animate={{ scale: 1, opacity: 1, y: 0 }}
                    exit={{ scale: 0.9, opacity: 0, y: 20 }}
                    transition={{ type: 'spring', damping: 25, stiffness: 300 }}
                    className="relative z-10 w-full max-w-[800px] min-h-[500px] bg-(--surface) border border-(--border) rounded-[24px] overflow-hidden flex flex-col shadow-[0_32px_120px_rgba(0,0,0,0.8),0_0_0_1px_rgba(255,255,255,0.03)_inset]"
                >
                    {/* Titlebar */}
                    <div className="h-[52px] bg-(--surface) border-b border-(--border) flex items-center px-[18px] gap-3.5 shrink-0">
                        <div className="w-8 h-8 rounded-lg bg-(--amber) grid place-items-center text-(--bg) shadow-[0_2px_12px_rgba(232,160,32,0.3)] select-none">
                            <Sparkles size={16} />
                        </div>
                        <div className="title-meta">
                            <div className="text-[13px] font-bold text-(--text) tracking-tight">Research Synthesis</div>
                            <div className="flex items-center gap-1.5 font-mono text-[10px] text-(--muted) tracking-widest uppercase">
                                <div className={`w-1.5 h-1.5 rounded-full bg-(--amber) ${loading ? 'animate-pulse' : ''}`} />
                                {loading ? 'Generating comprehensive report...' : result ? 'Synthesis complete' : 'Configure synthesis engine'}
                            </div>
                        </div>
                        <button 
                            onClick={onClose}
                            className="ml-auto w-[28px] h-[28px] rounded-md border border-(--border) bg-(--raised) text-(--muted) grid place-items-center text-lg hover:bg-red-500/10 hover:border-red-500/30 hover:text-red-500 transition-all leading-none"
                        >
                            &times;
                        </button>
                    </div>

                    <div className="flex-1 relative flex flex-col items-center justify-center p-10">
                        <AnimatePresence mode="wait">
                            {loading ? (
                                <motion.div 
                                    key="loading"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    exit={{ opacity: 0, y: -10 }}
                                    className="flex flex-col items-center"
                                >
                                    {/* Orbital Loader */}
                                    <div className="relative w-[120px] h-[120px] mb-9">
                                        <div className="absolute inset-0 rounded-full border border-(--amber)/10" />
                                        <motion.div 
                                            animate={{ rotate: 360 }}
                                            transition={{ duration: 1.4, ease: [0.5, 0.1, 0.5, 0.9], repeat: Infinity }}
                                            className="absolute inset-[6px] rounded-full border-2 border-transparent border-t-(--amber) border-r-(--amber)/30 shadow-[0_0_16px_rgba(232,160,32,0.2)]"
                                        />
                                        <motion.div 
                                            animate={{ rotate: -360 }}
                                            transition={{ duration: 2, ease: [0.5, 0.1, 0.5, 0.9], repeat: Infinity }}
                                            className="absolute inset-[18px] rounded-full border-[1.5px] border-transparent border-b-(--amber)/40 border-l-(--amber)/15"
                                        />
                                        <div className="absolute inset-0 flex items-center justify-center">
                                            <motion.div 
                                                animate={{ boxShadow: ['0 4px 20px rgba(0,0,0,0.5)', '0 4px 28px rgba(232,160,32,0.2), 0 0 0 4px rgba(232,160,32,0.05)', '0 4px 20px rgba(0,0,0,0.5)'] }}
                                                transition={{ duration: 2, ease: 'easeInOut', repeat: Infinity }}
                                                className="w-[44px] h-[44px] rounded-xl bg-(--raised) border border-(--border2) grid place-items-center text-xl shadow-[0_4px_20px_rgba(0,0,0,0.5)]"
                                            >
                                                ✦
                                            </motion.div>
                                        </div>
                                        {/* Orbiting Dots */}
                                        {[0, 1, 2].map((i) => (
                                            <motion.div
                                                key={i}
                                                animate={{ rotate: 360 }}
                                                transition={{ duration: 3, ease: 'linear', repeat: Infinity, delay: -i }}
                                                className="absolute inset-0 pointer-events-none"
                                            >
                                                <div 
                                                    className="absolute top-1/2 left-1/2 w-1.5 h-1.5 rounded-full bg-(--amber) shadow-[0_0_8px_rgba(232,160,32,0.4)]" 
                                                    style={{ transform: `translate(-3px, -3px) translateY(52px) scale(${1 - i * 0.2})`, opacity: 1 - i * 0.3 }} 
                                                />
                                            </motion.div>
                                        ))}
                                    </div>

                                    <h2 className="text-[22px] font-extrabold tracking-tight text-(--text) text-center mb-2.5">Synthesizing Research</h2>
                                    <p className="font-mono text-[11px] text-(--sub) text-center leading-relaxed max-w-[340px] mb-8 tracking-wide">
                                        AI is analyzing collected contexts,<br />merging topics, and validating sources...
                                    </p>

                                    {/* Steps */}
                                    <div className="flex items-center gap-1.5 mb-8">
                                        {STEPS.map((step, i) => (
                                            <React.Fragment key={step.id}>
                                                <div className={`
                                                    flex items-center gap-[7px] px-3 py-1.5 rounded-full border font-mono text-[10px] tracking-widest transition-all
                                                    ${activeStepIndex > i ? 'border-emerald-500/30 bg-emerald-500/5 text-emerald-500' : 
                                                      activeStepIndex === i ? 'border-(--amber)/30 bg-(--amber)/5 text-(--amber)' : 
                                                      'border-(--border) bg-(--raised) text-(--muted)'}
                                                `}>
                                                    <span className="text-[11px]">{activeStepIndex > i ? '✓' : activeStepIndex === i ? '⟳' : '◎'}</span>
                                                    {step.label}
                                                </div>
                                                {i < STEPS.length - 1 && <span className="text-(--muted) font-mono text-[10px]">&rarr;</span>}
                                            </React.Fragment>
                                        ))}
                                    </div>

                                    {/* Progress Bar */}
                                    <div className="w-[320px]">
                                        <div className="flex justify-between items-center mb-2 font-mono text-[10px] tracking-widest uppercase">
                                            <span className="text-(--muted)">PROCESSING</span>
                                            <span className="text-(--amber) font-semibold">{Math.round(progress)}%</span>
                                        </div>
                                        <div className="w-full h-1 bg-(--raised) rounded-full overflow-hidden border border-(--border)/30">
                                            <motion.div 
                                                className="h-full bg-linear-to-r from-(--amber2) to-(--amber) shadow-[0_0_8px_rgba(232,160,32,0.4)]"
                                                animate={{ width: `${progress}%` }}
                                                transition={{ duration: 0.3 }}
                                            />
                                        </div>
                                    </div>

                                    {/* Meta Row */}
                                    <div className="flex items-center gap-5 mt-5 font-mono text-[10px] text-(--muted) tracking-widest">
                                        <div className="flex items-center gap-1.5">Nodes <span className="text-(--sub) font-bold">{nodes.length}</span></div>
                                        <div className="w-px h-3 bg-(--border)" />
                                        <div className="flex items-center gap-1.5">Selected <span className="text-(--sub) font-bold">{selectedCount}</span></div>
                                        <div className="w-px h-3 bg-(--border)" />
                                        <div className="flex items-center gap-1.5">Est. <span className="text-(--sub) font-bold">~{Math.max(5, 12 - Math.floor(progress/10))}s</span></div>
                                    </div>
                                </motion.div>
                            ) : result ? (
                                <motion.div 
                                    key="result"
                                    initial={{ opacity: 0, scale: 0.98 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className="w-full h-full flex flex-col"
                                >
                                    <div className="flex-1 flex flex-col overflow-hidden">
                                        <div className="flex items-center justify-between mb-4">
                                            <div className="flex items-center gap-3">
                                                <div className="px-3 py-1 bg-(--amber)/10 text-(--amber) border border-(--amber)/20 rounded-lg text-[11px] font-bold tracking-widest uppercase">
                                                    Analysis Result
                                                </div>
                                                <div className="text-[11px] text-(--muted) font-mono">{sources.length} sources utilized</div>
                                            </div>
                                            <div className="flex gap-1.5">
                                                <button onClick={handleDownloadMarkdown} className="p-2 hover:bg-(--raised) rounded-lg text-(--sub) hover:text-(--text) border border-transparent hover:border-(--border) transition-all" title="Download Markdown"><FileDown size={14} /></button>
                                                <button onClick={handleCopy} className="p-2 hover:bg-(--raised) rounded-lg text-(--sub) hover:text-(--text) border border-transparent hover:border-(--border) transition-all" title="Copy Content">{copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}</button>
                                            </div>
                                        </div>

                                        <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar">
                                            <div className="prose prose-sm prose-invert max-w-none">
                                                <div className="text-sm text-(--text) leading-relaxed whitespace-pre-wrap bg-(--raised)/30 border border-(--border)/50 p-6 rounded-[18px]">
                                                    {result}
                                                </div>
                                            </div>
                                        </div>

                                        <div className="mt-6 pt-6 border-t border-(--border) flex gap-3">
                                            <div className="relative flex-1">
                                                <input
                                                    type="text"
                                                    placeholder="Ask for deeper analysis or specific details..."
                                                    value={query}
                                                    onChange={(e) => setQuery(e.target.value)}
                                                    onKeyDown={(e) => e.key === 'Enter' && handleSynthesize()}
                                                    className="w-full bg-(--raised) border border-(--border) rounded-xl px-4 py-3 text-sm text-(--text) placeholder-(--muted) focus:outline-none focus:border-(--amber)/50 transition-all font-mono"
                                                />
                                            </div>
                                            <button
                                                onClick={handleSynthesize}
                                                disabled={!query.trim()}
                                                className="px-5 py-3 bg-(--raised) border border-(--border) hover:border-(--amber)/50 text-(--text) font-bold rounded-xl flex items-center gap-2 hover:bg-(--surface) disabled:opacity-50 transition-all text-[12px] tracking-widest uppercase"
                                            >
                                                Refine Engine <ArrowRight size={14} className="text-(--amber)" />
                                            </button>
                                            <button
                                                onClick={handleSaveToCanvas}
                                                disabled={saving}
                                                className="px-5 py-3 bg-(--amber) text-(--bg) font-bold rounded-xl flex items-center gap-2 hover:bg-(--amber2) transition-all text-[12px] tracking-widest uppercase shadow-[0_4px_20px_rgba(232,160,32,0.3)]"
                                            >
                                                {saving ? <Loader2 size={14} className="animate-spin" /> : <Target size={14} />}
                                                Save to Canvas
                                            </button>
                                        </div>
                                    </div>
                                </motion.div>
                            ) : (
                                <motion.div 
                                    key="input"
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    className="flex flex-col items-center justify-center max-w-[480px]"
                                >
                                    <div className="w-[56px] h-[56px] rounded-2xl bg-(--amber)/10 border border-(--amber)/30 flex items-center justify-center text-(--amber) mb-6 shadow-[0_0_24px_rgba(232,160,32,0.1)]">
                                        <Sparkles size={24} />
                                    </div>
                                    <h2 className="text-[24px] font-black tracking-tight text-(--text) text-center mb-2">Research Synthesizer</h2>
                                    <p className="text-[12px] text-(--sub) text-center leading-relaxed mb-10 max-w-[360px]">
                                        Analyze all selected research nodes to generate a comprehensive synthesis report.
                                    </p>

                                    <div className="w-full relative flex flex-col gap-4">
                                        <div className="relative">
                                            <input
                                                autoFocus
                                                type="text"
                                                placeholder="What should I analyze for you?"
                                                value={query}
                                                onChange={(e) => setQuery(e.target.value)}
                                                onKeyDown={(e) => e.key === 'Enter' && handleSynthesize()}
                                                className="w-full h-[52px] bg-(--raised) border border-(--border) rounded-2xl px-5 text-sm text-(--text) placeholder-(--muted) focus:outline-none focus:border-(--amber)/50 transition-all font-mono"
                                            />
                                            <div className="absolute right-3 top-1/2 -translate-y-1/2 px-2 py-1 bg-(--surface) border border-(--border) rounded-md text-[9px] text-(--muted) font-mono uppercase tracking-widest">
                                                Enter
                                            </div>
                                        </div>

                                        <button
                                            onClick={handleSynthesize}
                                            disabled={!query.trim()}
                                            className="w-full h-[52px] bg-(--amber) text-(--bg) font-black rounded-2xl flex items-center justify-center gap-2.5 text-[13px] tracking-widest uppercase shadow-[0_4px_28px_rgba(232,160,32,0.3)] hover:bg-(--amber2) hover:-translate-y-px transition-all disabled:opacity-50 disabled:translate-y-0"
                                        >
                                            Initialize Synthesis Engine <ArrowRight size={16} />
                                        </button>

                                        <div className="flex items-center justify-between px-2 font-mono text-[9px] text-(--muted) tracking-widest uppercase">
                                            <div className="flex items-center gap-2">
                                                <div className="w-1 h-1 rounded-full bg-emerald-500" />
                                                Ready to Process
                                            </div>
                                            <div>{selectedCount} Selected Hubs</div>
                                        </div>
                                    </div>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>

                    {/* Styled Scrollbar CSS */}
                    <style jsx global>{`
                        .custom-scrollbar::-webkit-scrollbar {
                            width: 4px;
                        }
                        .custom-scrollbar::-webkit-scrollbar-track {
                            background: transparent;
                        }
                        .custom-scrollbar::-webkit-scrollbar-thumb {
                            background: var(--border);
                            border-radius: 10px;
                        }
                        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
                            background: var(--muted);
                        }
                    `}</style>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}
