"use client";

import React, { useState } from 'react';
import { useGraphStore } from '@/store/graph.store';

export function SynthesisViewer() {
  const synthesisAst = useGraphStore(state => state.synthesisAst);
  const [showJson, setShowJson] = useState(false);

  if (!synthesisAst) {
    return (
      <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', background: 'var(--bg)', color: 'var(--text)', fontFamily: 'var(--font-playfair), serif', textAlign: 'center' }}>
        <div style={{ color: 'var(--text-muted)', fontSize: '14px', marginTop: '100px', fontFamily: 'var(--font-dm-mono)' }}>
          No synthesis report available yet. Run the Synthesis Pipeline first.
        </div>
      </div>
    );
  }

  const { title, sections, references } = synthesisAst;

  return (
    <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', background: 'var(--bg)', color: 'var(--text)', fontFamily: 'var(--font-playfair), serif' }}>
      <header style={{ marginBottom: '40px', borderBottom: '1px solid var(--border)', paddingBottom: '20px' }}>
        <h1 style={{ fontSize: '32px', marginBottom: '12px' }}>{title || 'Synthesis Report'}</h1>
        <div style={{ display: 'flex', gap: '16px', fontSize: '12px', fontFamily: 'var(--font-dm-mono), monospace', color: 'var(--text-muted)' }}>
          <span>Generated by: Cognode Engine</span>
          {references && Array.isArray(references) && <span>Sources: {references.length}</span>}
        </div>
      </header>

      {showJson ? (
        <pre style={{ background: 'var(--surface)', padding: '20px', borderRadius: '8px', fontSize: '12px', color: 'var(--amber-l)', overflowX: 'auto', fontFamily: 'var(--font-dm-mono)' }}>
          {JSON.stringify(synthesisAst, null, 2)}
        </pre>
      ) : (
        <>
          {sections && Array.isArray(sections) && sections.map((sec: {heading: string, content: string}, idx: number) => (
            <section key={idx} style={{ marginBottom: '32px' }}>
              <h2 style={{ fontSize: '20px', color: 'var(--amber-l)', marginBottom: '16px' }}>{sec.heading}</h2>
              <div style={{ fontSize: '14px', lineHeight: 1.8, color: 'var(--text-mid)', fontFamily: 'var(--font-sans)', whiteSpace: 'pre-wrap' }}>
                {sec.content}
              </div>
            </section>
          ))}

          {references && Array.isArray(references) && references.length > 0 && (
            <section style={{ marginBottom: '32px' }}>
              <h2 style={{ fontSize: '20px', color: 'var(--amber-l)', marginBottom: '16px' }}>Bibliography</h2>
              <div style={{ fontSize: '12px', fontFamily: 'var(--font-dm-mono), monospace', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {references.map((ref: {id: string, title: string, url: string}, idx: number) => (
                  <div key={idx}>[{idx + 1}] {ref.title} {ref.url && <a href={ref.url} style={{ color: 'var(--blue)' }} target="_blank" rel="noreferrer">{ref.url}</a>}</div>
                ))}
              </div>
            </section>
          )}
        </>
      )}

      <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid var(--border)', display: 'flex', gap: '12px' }}>
         <button style={{ background: 'var(--amber)', color: 'var(--bg)', border: 'none', padding: '8px 16px', borderRadius: '4px', fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-dm-mono)' }}>Export PDF</button>
         <button 
           onClick={() => setShowJson(!showJson)}
           style={{ background: 'transparent', color: 'var(--text)', border: '1px solid var(--border)', padding: '8px 16px', borderRadius: '4px', fontSize: '12px', cursor: 'pointer', fontFamily: 'var(--font-dm-mono)' }}
         >
           {showJson ? 'View Rendering' : 'View JSON AST'}
         </button>
      </div>
    </div>
  );
}
