name: Build Validation

on:
  pull_request:
    paths:
      - "apps/**"
      - "packages/**"
      - "*.json"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci --legacy-peer-deps
      - run: npx turbo run build
