name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Web Dashboard Deployment
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: ${{ secrets.RENDER_WEB_DEPLOY_HOOK }}
          method: 'POST'
          timeout: 10000
          
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deployment
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
          method: 'POST'
          timeout: 10000
