name: Test

on:
  pull_request:
    paths:
      - "apps/**"
      - "packages/**"
      - "*.json"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: apps/backend/requirements.txt

      - run: npm ci --legacy-peer-deps
      - run: pip install -r apps/backend/requirements.txt

      - run: npx turbo run test
